version: "2"
services:
  k8s-deployer-env:
    build: .
    image: evns/k8s-deployer
    environment:
      - MASTER_HOST=...
      - CA_DATA=...
      - CLIENT_KEY=...
      - CLIENT_DATA=...

  k8s-deployer-mount:
    build: .
    image: evns/k8s-deployer
    volumes:
      - ~/.kube/config:/root/.kube/config